version: "3"

services:
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - './data:/data/db'
  application:
    build: .
    command: npm run dev
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/app
    depends_on:
      - db
