name: ci-nodejs-workflow
on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
      - name: Run docker-compose
        run: docker-compose up -d
      - name: Run tests
        run: npm run test
